### ISSUE TITLE
`--local_cutax` doesn't work on midway3

### ISSUE THREAD

**Issue by FaroutYLq** [XENONnT/env_starter#29]
Not sure this is a problem within `env_starter`
```  | module | version | path | git
-- | -- | -- | -- | --
python | 3.9.16 | /opt/XENONnT/anaconda/envs/XENONnT_development... | None
strax | 1.5.1 | /opt/XENONnT/anaconda/envs/XENONnT_development... | None
straxen | 2.1.0 | /opt/XENONnT/anaconda/envs/XENONnT_development... | None
cutax | 1.15.0 | /dali/lgrandi/xenonnt/software/cutax/v1.15.0/c... | None```

**Comment by FaroutYLq** [comment]
The issue might be rooted[ here instead](https://github.com/XENONnT/base_environment/blob/17b1e82dc0856ac4c8cb0e803f244a1d9ffd95d3/create-env#L242-L243). Need to add a MIDWAY3 path.

**Comment by FaroutYLq** [comment]
Trying `--local_cutax`:
- On Midway2(worked):```print(os.environ['PATH'])
>>>/opt/XENONnT/anaconda/envs/XENONnT_development/bin:/opt/rh/devtoolset-9/root/usr/bin:/usr/bin:/usr/local/bin
print(os.environ['PYTHONPATH'])
>>>
print(os.environ['CUTAX_LOCATION'])
>>>/dali/lgrandi/xenonnt/software/cutax/v1.15.0
print(os.environ['INSTALL_CUTAX'])
>>>0```
- On Midway2(didn't work):```print(os.environ['PATH'])
>>>/opt/XENONnT/anaconda/envs/XENONnT_development/bin:/opt/XENONnT/anaconda/condabin:/opt/rh/devtoolset-9/root/usr/bin:/usr/bin:/usr/local/bin
print(os.environ['PYTHONPATH'])
>>>/dali/lgrandi/xenonnt/software/cutax/v1.15.0:
print(os.environ['CUTAX_LOCATION'])
>>>/dali/lgrandi/xenonnt/software/cutax/v1.15.0
print(os.environ['INSTALL_CUTAX'])
>>>1```

**Comment by FaroutYLq** [comment]
Reading[ this part](https://github.com/XENONnT/base_environment/blob/17b1e82dc0856ac4c8cb0e803f244a1d9ffd95d3/create-env#L241-L261), seems that the issue is `INSTALL_CUTAX` is not propagated at all.

**Comment by FaroutYLq** [comment]
> Reading[ this part](https://github.com/XENONnT/base_environment/blob/17b1e82dc0856ac4c8cb0e803f244a1d9ffd95d3/create-env#L241-L261), seems that the issue is `INSTALL_CUTAX` is not propagated at all.

This hypothesis is correct:
```
yuanlq@midway3-login3:~$ export INSTALL_CUTAX=0
yuanlq@midway3-login3:~$ module load singularity&&singularity shell --contain --bind /home/yuanlq --bind /project2/lgrandi/xenonnt/dali:/dali --bind /project2 --bind /project/ --bind /scratch/midway2/yuanlq --bind /scratch/midway3/yuanlq /project2/lgrandi/xenonnt/singularity-images/xenonnt-development.simg
INFO:    Converting SIF file to temporary sandbox...

(XENONnT_development) Singularity xenonnt-development.simg:~> echo $INSTALL_CUTAX
1
```

**Comment by FaroutYLq** [comment]
Draft solution below failed on midway3... no idea why 
<img width="816" alt="image" src="https://github.com/XENONnT/reprox/assets/47046530/c7de6175-132e-414e-8316-0390d742d26b">

**Comment by FaroutYLq** [comment]
Dirty solution working [here](https://xe1t-wiki.lngs.infn.it/doku.php?id=xenon:xenonnt:analysis:analysis_tools_team:midway_tutorial#midway3_faq)

**Comment by yuema137** [comment]
I think within the scope of env_starter we should encourage people to use `sys.path.insert`
